[package]
name = "tao-os"
version = "0.0.1"
authors = ["gcarvellas"]

[workspace]

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
spin = "0.9.8"
volatile = "0.2.6"

[lib]
name = "kernel"
crate-type = ["staticlib"]
