
name: Audit, Lint, Build

on:
  push:
    branches:
      - '**' # This means the workflow will run on any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm xorriso grub-pc-bin grub-common cargo-audit

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
        target: x86_64-unknown-none
        components: rustfmt, clippy, audit

    - name: Cargo Rustfmt
      run: cargo +nightly fmt

    - name: Cargo Audit
      run: cargo audit

    - name: Cargo Clippy
      run: cargo clippy

    - name: Build
      run: make clean && make all
