
name: Audit, Lint, Build

on:
  push:
    branches:
      - '**' # This means the workflow will run on any branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout GitHub Action"
      uses: actions/checkout@v2

    - name: "Set up Rust"
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.80.1
        target: x86_64-unknown-none

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y nasm xorriso grub-pc-bin grub-common cargo-audit

    - name: Cargo Audit
      run: cargo audit

    - name: Install Clippy
      run: rustup component add clippy

    - name: Cargo Clippy
      run: cargo clippy

    - name: Build
      run: make clean && make all
